In [2]:
import pymongo
from pymongo import MongoClient
client = MongoClient()

In [4]:
client.list_database_names()

['admin', 'config', 'local', 'studentDetails', 'test']

In [12]:
db = client.test

In [19]:
db.list_collection_names()
student = db.student

In [21]:
for x in student.find():
    print(x)

{'_id': ObjectId('647ab4b8d200223376e712bf'), 'Name': 'Prabhjeet', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c0'), 'Name': 'Rahul', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c1'), 'Name': 'Dev', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c2'), 'Name': 'Jagpreet', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647e6144653f9587f7d551a2'), 'Name': 'Integer Course', 'program': 123, 'city': 'Toronto'}
{'_id': '647ab4b8d200223376e712bf', 'Name': 'Sumit', 'program': 'AIML', 'city': 'Toronto'}
{'_id': "ObjectId('647e6144653f9587f7d551a2')", 'Name': 'Sumit1', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647e7c2a653f9587f7d551a3'), 'Name': 'ALLen', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647e7c30653f9587f7d551a4'), 'Name': 'Aleen', 'program': 'AIML', 'city': 'Toronto'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'addres

***Not equal to query***

In [32]:
myquery = {
    "$and":[
        {
            "address":{"$regex":"^Y"}
        },
        {
            "address":{"$regex":"1"}
        },
        {
            "name":{"$ne":"Nicky"}
        }
    ]
}

mydoc = student.find(myquery)
for x in mydoc:
    print(x)

print("\nTotal Count of Records matching query", mydoc.retrieved)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}

Total Count of Records matching query 2


***gt, lt, gte, lte***

In [50]:
myquery = {
            "address":{"$gt":"S"}
        }
mydoc = student.find(myquery)
for x in mydoc:
    print(x)



{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}


***Sorting***

In [58]:
mydoc = student.find().sort('name',-1)

for x in mydoc:
    print(x)

{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': ObjectId('647ab4b8d200223376e712bf'), 'Name': 'Prabhjeet', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c0'), 'Name': 'Rahul', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c1'), 'Name': 'Dev', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647bb277d200223376e712c2'), 'Name': 'Jagpreet', 'program': 'AIML', 'city': 'Toronto'}
{'_id': ObjectId('647e6144653f9587f7d551a2'), 'Name': 'Integer Course', 'program': 123, 'c

***Update single document***

In [80]:
myquery = {'address':'Canyon 1234'}

print("Finding documents")
for x in student.find(myquery):
    print(x)

print('\n')

newvalues = {'$set':{'address':'Canyon 123'}}
student.update_one(myquery, newvalues)

newquery = {'address':'Canyon 123'}

print("Finding old documents")
for x in student.find(myquery):
    print(x)

print('\n')


print("Finding updated documents")
for x in student.find(newquery):
    print(x)

Finding documents
{'_id': 5, 'name': 'Michael', 'address': 'Canyon 1234'}


Finding old documents


Finding updated documents
{'_id': 5, 'name': 'Michael', 'address': 'Canyon 123'}


***Update Multiple Document***

In [88]:
myquery = {'name':{'$regex':'^M'}}

print("Finding documents")
for x in student.find(myquery):
    print(x)
print('\n')

newvalues = {'$set':{'name':'Anna'}}
x = student.update_many(myquery, newvalues)
print('\n')

print(x.modified_count)

myquery = {'name':{'$regex':'^A'}}
print("Finding updated documents")
for x in student.find(myquery):
    print(x)



Finding documents




0
Finding updated documents
{'_id': 3, 'name': 'Anna', 'address': 'Close st 652'}
{'_id': 5, 'name': 'Anna', 'address': 'Canyon 123'}


***Delete documents***

In [136]:
# # Delete first occurrence of the records having Name as Aleen
# myquery = { "Name": "Aleen" }
# student.delete_one(myquery)

# Deleting all  records having Name as Aleen
myquery = { "name": "John" }
x = student.delete_many(myquery)

print('Count of records deleted', x.deleted_count)

for x in student.find():
    print(x)

records = [
    {'_id': 1, 'name': 'John', 'address': 'Highway 37'},
    {'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'},
    {'_id': 3, 'name': 'Amy', 'address': 'Close st 652'},
    {'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'},
    {'_id': 5, 'name': 'Michael', 'address': 'Valley 345'},
    {'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'},
    {'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'},
    {'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'},
    {'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'},
    {'_id': 10, 'name': 'John', 'address': 'Highway 37'},
    {'_id': 11, 'name': 'John', 'address': 'Lowstreet 27'},
    {'_id': 12, 'name': 'John', 'address': 'Close st 652'},
    {'_id': 13, 'name': 'John', 'address': 'Mountain 21'}]
student.insert_many(records)

Count of records deleted 0


***Removing field***

In [114]:
student.update_many({}, {'$unset': {'address':""}})

for x in student.find():
    print(x)

{'_id': 1, 'last_name': 'John'}
{'_id': 2, 'first_name': 'Peter'}
{'_id': 3, 'first_name': 'Anna'}
{'_id': 4, 'first_name': 'Hannah'}
{'_id': 5, 'first_name': 'Anna'}
{'_id': 6, 'first_name': 'Vicky'}
{'_id': 7, 'first_name': 'Nicky'}
{'_id': 8, 'first_name': 'Nancy'}
{'_id': 9, 'first_name': 'Viola'}


***Removing all documents***

In [134]:
x = student.delete_many({})

for x in student.find():
    print(x)

print('Count of records deleted', x.deleted_count)


Count of records deleted 13


***Updating field name***

In [103]:
# # Update field name for all records
# student.update_many( 
#   { }, 
#   { '$rename': { "first_name": "last_name" } } 
# )

# Update field name for only specific records
student.update_many( 
  {'address': 'Highway 37' }, 
  { '$rename': { "first_name": "last_name" } } 
)

for x in student.find():
    print(x)

{'_id': 1, 'address': 'Highway 37', 'last_name': 'John'}
{'_id': 2, 'address': 'Lowstreet 27', 'first_name': 'Peter'}
{'_id': 3, 'address': 'Close st 652', 'first_name': 'Anna'}
{'_id': 4, 'address': 'Mountain 21', 'first_name': 'Hannah'}
{'_id': 5, 'address': 'Canyon 123', 'first_name': 'Anna'}
{'_id': 6, 'address': 'Yellow Garden 124', 'first_name': 'Vicky'}
{'_id': 7, 'address': 'Yellow Garden 23', 'first_name': 'Nicky'}
{'_id': 8, 'address': 'Younge Ave. 123', 'first_name': 'Nancy'}
{'_id': 9, 'address': 'Sideway Ave', 'first_name': 'Viola'}


***Removing collection name***

In [128]:
client.list_database_names()
db1 = client.studentDetails
db1.list_collection_names()
# test = db1.AIML
# test.drop()

[]

In [139]:
for x in student.find():
    print(x)

{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': 10, 'name': 'John', 'address': 'Highway 37'}
{'_id': 11, 'name': 'John', 'address': 'Lowstreet 27'}
{'_id': 12, 'name': 'John', 'address': 'Close st 652'}
{'_id': 13, 'name': 'John', 'address': 'Mountain 21'}


***Vectors***

In [175]:
import numpy as np
vector_row = np.array([1,2,3,4,5,4,6])

***Selecting elements in vectors***

In [133]:
vector_row[1]

2

In [148]:
print(type(vector_row[3]), ":",vector_row[3])

print(type(vector_row[:3]), ":",vector_row[:3])

print(vector_row[:4])


<class 'numpy.int32'> : 4
<class 'numpy.ndarray'> : [1 2 3]
[1 2 3 4]


In [176]:
print(vector_row[-3])
print(vector_row[:-3])
print(vector_row[:-2])
print(vector_row[2:-2])
print()
np.where(vector_row==4)

5
[1 2 3 4]
[1 2 3 4 5]
[3 4 5]



(array([3, 5], dtype=int64),)

***Matrices***

In [200]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# prinitng whole matrix
print(matrix)

# Selecting element from matrix
print(matrix[2,2],' : ',matrix[-1,-1])
print(matrix[1:,1:])
print(matrix[-2:,-2:])

print('Shape of Matrix', matrix.shape)
print('Size of Matrix', matrix.size)
print('Dimension of Matrix', matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9  :  9
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
Shape of Matrix (3, 3)
Size of Matrix 9
Dimension of Matrix 2


In [210]:
vector_a = np.array([[1,1,1],
                  [1,1,1],
                  [1,1,1]])
vector_b = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])


***Addition of Matrices***

In [211]:
np.add(vector_a,vector_b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

***Subtraction of Matrices***

In [206]:
np.subtract(vector_a,vector_b)

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

***Multiplication of Matrices***

In [209]:
np.matmul(vector_a,vector_b)

array([[12, 15, 18],
       [12, 15, 18],
       [12, 15, 18]])

***Dot product of Matrices***

In [207]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a,vector_b)

32

***Function to multiply two Matrices entered by the user***

In [218]:
rows = int(input('Enter number of rows for first matrix'))
cols = int(input('Enter number of cols for first matrix'))
a= [[]]
print('Enter first matrix elements')
for i in range(rows):
    for j in range(cols):
        a[i][j] = input(i,',',j,'element')

Enter first matrix elements


TypeError: Kernel.raw_input() takes from 1 to 2 positional arguments but 5 were given